services:
  postgres:
    image: postgres:16.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-subaggr}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 3s
      retries: 3
  subaggr:
    build: .
    ports: 
      - "8000:${SERVER_PORT:-8000}"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8000}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-subaggr}
      GIN_MODE: ${GIN_MODE:-release}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app
volumes:
  pgdata: {}