services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 3s
      retries: 3
  subaggr:
    build: .
    ports: 
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GIN_MODE: ${GIN_MODE:-release}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app